# -*- coding: utf-8 -*-

import names


def main():
    startApplication("textedit")
    type(waitForObject(names.untitled_txt_Rich_Text_Format_Actions_QTextEdit), "hi,")
    type(waitForObject(names.untitled_txt_Rich_Text_Format_Actions_QTextEdit), "<Return>")
    type(waitForObject(names.untitled_txt_Rich_Text_Format_Actions_QTextEdit), "<Return>")
    type(waitForObject(names.untitled_txt_Rich_Text_Format_Actions_QTextEdit), "qho")
    doubleClick(waitForObject(names.untitled_txt_Rich_Text_Format_Actions_QTextEdit), 12, 51, Qt.NoModifier, Qt.LeftButton)
    clickButton(waitForObject(names.untitled_txt_Rich_Text_Bold_QToolButton))
    mouseClick(waitForObject(names.untitled_txt_Rich_Text_Format_Actions_QTextEdit), 59, 46, Qt.NoModifier, Qt.LeftButton)
    type(waitForObject(names.untitled_txt_Rich_Text_Format_Actions_QTextEdit), " are")
    doubleClick(waitForObject(names.untitled_txt_Rich_Text_Format_Actions_QTextEdit), 37, 45, Qt.NoModifier, Qt.LeftButton)
    clickButton(waitForObject(names.untitled_txt_Rich_Text_Italic_QToolButton))
    mouseClick(waitForObject(names.untitled_txt_Rich_Text_Format_Actions_QTextEdit), 102, 43, Qt.NoModifier, Qt.LeftButton)
    type(waitForObject(names.untitled_txt_Rich_Text_Format_Actions_QTextEdit), " you")
    doubleClick(waitForObject(names.untitled_txt_Rich_Text_Format_Actions_QTextEdit), 60, 46, Qt.NoModifier, Qt.LeftButton)
    clickButton(waitForObject(names.untitled_txt_Rich_Text_Underline_QToolButton))
    mouseClick(waitForObject(names.untitled_txt_Rich_Text_Format_Actions_QTextEdit), 118, 41, Qt.NoModifier, Qt.LeftButton)
    type(waitForObject(names.untitled_txt_Rich_Text_Format_Actions_QTextEdit), "?")
    doubleClick(waitForObject(names.untitled_txt_Rich_Text_Format_Actions_QTextEdit), 74, 43, Qt.NoModifier, Qt.LeftButton)
    doubleClick(waitForObject(names.untitled_txt_Rich_Text_Format_Actions_QTextEdit), 74, 43, Qt.NoModifier, Qt.LeftButton)
    doubleClick(waitForObject(names.untitled_txt_Rich_Text_Format_Actions_QTextEdit), 74, 43, Qt.NoModifier, Qt.LeftButton)
    doubleClick(waitForObject(names.untitled_txt_Rich_Text_Format_Actions_QTextEdit), 74, 43, Qt.NoModifier, Qt.LeftButton)
    doubleClick(waitForObject(names.untitled_txt_Rich_Text_Format_Actions_QTextEdit), 74, 43, Qt.NoModifier, Qt.LeftButton)
    mouseClick(waitForObject(names.untitled_txt_Rich_Text_Format_Actions_QTextEdit), 74, 43, Qt.NoModifier, Qt.LeftButton)
    clickButton(waitForObject(names.untitled_txt_Rich_Text_Center_QToolButton))
    doubleClick(waitForObject(names.untitled_txt_Rich_Text_comboSize_QComboBox), 25, -10, Qt.NoModifier, Qt.LeftButton)
    doubleClick(waitForObject(names.untitled_txt_Rich_Text_comboSize_QComboBox), 25, -10, Qt.NoModifier, Qt.LeftButton)
    type(waitForObject(names.untitled_txt_Rich_Text_comboSize_QComboBox), "<Backspace>")
    type(waitForObject(names.untitled_txt_Rich_Text_comboSize_QComboBox), "1")
    type(waitForObject(names.untitled_txt_Rich_Text_comboSize_QComboBox), "0")
    type(waitForObject(names.untitled_txt_Rich_Text_comboSize_QComboBox), "<Return>")
    type(waitForObject(names.untitled_txt_Rich_Text_comboSize_QComboBox), "<Backspace>")
    type(waitForObject(names.untitled_txt_Rich_Text_comboSize_QComboBox), "8")
    type(waitForObject(names.untitled_txt_Rich_Text_comboSize_QComboBox), "<Return>")
    sendEvent("QCloseEvent", waitForObject(names.untitled_txt_Rich_Text_TextEdit))
    clickButton(waitForObject(names.application_Discard_QPushButton))
